"""added topic and grade columns

Revision ID: a85959325a38
Revises: adccea42d7b6
Create Date: 2024-12-12 20:47:13.767418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a85959325a38'
down_revision: Union[str, None] = 'adccea42d7b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessonplans', sa.Column('topic', sa.String(), nullable=False))
    op.add_column('lessonplans', sa.Column('grade', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessonplans', 'grade')
    op.drop_column('lessonplans', 'topic')
    # ### end Alembic commands ###
